##eureka config
spring.application.name=api-gateway
#server.port=9003
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#eureka.instance.ip-address=localhost
#eureka.instance.prefer-ip-address=true
#eureka.instance.instance-id=${spring.application.name}:${server.port}:1

#server.servlet.context-path=/api/v1


spring.config.import=configserver:http://config-server:8888

