apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-service
spec:
  selector:
    matchLabels:
      app: bank-service
  template:
    metadata:
      labels:
        app: bank-service
    spec:
      containers:
      - name: bank-service
        image: chandrakesh17/bank-service
        resources:
          limits:
            memory: "400Mi"
            cpu: "500m"
          requests:
            memory: "200Mi"
            cpu: "200m"
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "k8s"
          - name: DB_SERVICE
            valueFrom:
              configMapKeyRef:
                name: my-config
                key: BANK_DB_SERVICE
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: BANK_DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: BANK_DB_PASSWORD
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: BANK_DB_NAME
        ports:
        - containerPort: 9001


---

apiVersion: v1
kind: Service
metadata:
  name: bank-service
spec:
  selector:
    app: bank-service
  ports:
  - port: 80
    targetPort: 9001

