eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka
eureka.instance.ip-address=localhost
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}:1