eureka:
  client:
    register-with-eureka: false
    fetch-registry: false


spring:
  cloud:
    config:
      server:
        git:
          uri: ${GITHUB_URI}
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_PAT}
          default-label: main

server:
  port: 8888
#Hello world